# Generated by Django 2.1 on 2019-07-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookChargeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_type', models.CharField(max_length=30)),
                ('days', models.IntegerField()),
                ('per_day_charge', models.FloatField()),
                ('min_charge', models.FloatField()),
                ('min_charge_days', models.IntegerField()),
            ],
        ),
    ]
