# Generated by Django 2.2.3 on 2019-07-26 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookChargeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_type', models.CharField(max_length=10)),
                ('book_type', models.CharField(max_length=30)),
                ('days', models.IntegerField()),
                ('per_day_charge', models.FloatField()),
                ('min_charge', models.FloatField()),
                ('min_charge_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('book_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookkeeping.BookChargeSheet')),
            ],
        ),
    ]
