version: '3'

services:
  django:
    container_name: django_server
    build:
      context: .
      dockerfile: Dockerfile
    image: docker_tutorial_django
    stdin_open: true
    tty: true
    command: bash -c "./entry.sh && python manage.py runserver [::]:8010"
    volumes:
      - .:/code
    ports:
      - "8010:8010"
